# Generated by Django 4.1 on 2024-01-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='foto',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
