# Generated by Django 4.1 on 2024-01-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_alter_fotografia_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='imagem',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotografias/'),
        ),
    ]
