# Generated by Django 4.1 on 2024-01-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0017_remove_fotografia_imagem_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='foto',
            new_name='fotografia',
        ),
    ]
