# Generated by Django 4.1 on 2024-01-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_rename_foto_fotografia_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='fotografia',
            new_name='foto',
        ),
    ]
