# Generated by Django 4.1 on 2024-01-09 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_rename_fotografia_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
