# Generated by Django 4.1 on 2024-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0021_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='favoritado',
            field=models.BooleanField(default=False),
        ),
    ]
